using Sqordia.Domain.Common;
using Sqordia.Domain.Enums;

namespace Sqordia.Domain.Entities.BusinessPlan;

/// <summary>
/// Represents a business plan or strategic plan
/// Adapts to different organization types
/// </summary>
public class BusinessPlan : BaseAuditableEntity
{
    public string Title { get; private set; } = null!;
    public string? Description { get; private set; }
    public BusinessPlanType PlanType { get; private set; }
    public BusinessPlanStatus Status { get; private set; }
    public Guid OrganizationId { get; private set; }
    public int Version { get; private set; }
    
    // Questionnaire completion tracking
    public int TotalQuestions { get; private set; }
    public int CompletedQuestions { get; private set; }
    public decimal CompletionPercentage { get; private set; }
    
    // AI Generation tracking
    public DateTime? QuestionnaireCompletedAt { get; private set; }
    public DateTime? GenerationStartedAt { get; private set; }
    public DateTime? GenerationCompletedAt { get; private set; }
    public string? GenerationModel { get; private set; }
    
    // Content sections (generated by AI, editable by user)
    public string? ExecutiveSummary { get; private set; }
    public string? ProblemStatement { get; private set; }
    public string? Solution { get; private set; }
    public string? MarketAnalysis { get; private set; }
    public string? CompetitiveAnalysis { get; private set; }
    public string? SwotAnalysis { get; private set; }
    public string? BusinessModel { get; private set; }
    public string? MarketingStrategy { get; private set; }
    public string? BrandingStrategy { get; private set; }
    public string? OperationsPlan { get; private set; }
    public string? ManagementTeam { get; private set; }
    public string? FinancialProjections { get; private set; }
    public string? FundingRequirements { get; private set; }
    public string? RiskAnalysis { get; private set; }
    public string? ExitStrategy { get; private set; }
    public string? AppendixData { get; private set; }
    
    // OBNL-specific sections
    public string? MissionStatement { get; private set; }
    public string? SocialImpact { get; private set; }
    public string? BeneficiaryProfile { get; private set; }
    public string? GrantStrategy { get; private set; }
    public string? SustainabilityPlan { get; private set; }
    
    // Metadata
    public DateTime? FinalizedAt { get; private set; }
    public DateTime? ArchivedAt { get; private set; }
    public bool IsTemplate { get; private set; }
    
    // Navigation properties
    public Organization Organization { get; private set; } = null!;
    public ICollection<QuestionnaireResponse> QuestionnaireResponses { get; private set; } = new List<QuestionnaireResponse>();
    public ICollection<FinancialProjection> FinancialProjectionDetails { get; private set; } = new List<FinancialProjection>();
    public ICollection<BusinessPlanShare> Shares { get; private set; } = new List<BusinessPlanShare>();
    public ICollection<BusinessPlanVersion> Versions { get; private set; } = new List<BusinessPlanVersion>();
    
    private BusinessPlan() { } // EF Core constructor
    
    public BusinessPlan(string title, BusinessPlanType planType, Guid organizationId, string? description = null)
    {
        Title = title ?? throw new ArgumentNullException(nameof(title));
        PlanType = planType;
        OrganizationId = organizationId;
        Description = description;
        Status = BusinessPlanStatus.Draft;
        Version = 1;
        TotalQuestions = 0;
        CompletedQuestions = 0;
        CompletionPercentage = 0;
        IsTemplate = false;
    }
    
    public void UpdateTitle(string title)
    {
        Title = title ?? throw new ArgumentNullException(nameof(title));
    }
    
    public void UpdateDescription(string? description)
    {
        Description = description;
    }
    
    public void UpdateQuestionnaire(int totalQuestions, int completedQuestions)
    {
        if (totalQuestions < 0 || completedQuestions < 0)
            throw new ArgumentException("Question counts must be non-negative");
            
        if (completedQuestions > totalQuestions)
            throw new ArgumentException("Completed questions cannot exceed total questions");
            
        TotalQuestions = totalQuestions;
        CompletedQuestions = completedQuestions;
        CompletionPercentage = totalQuestions > 0 ? (decimal)completedQuestions / totalQuestions * 100 : 0;
        
        if (completedQuestions == totalQuestions && totalQuestions > 0)
        {
            MarkQuestionnaireComplete();
        }
    }
    
    public void MarkQuestionnaireComplete()
    {
        if (Status == BusinessPlanStatus.Draft)
        {
            Status = BusinessPlanStatus.QuestionnaireComplete;
            QuestionnaireCompletedAt = DateTime.UtcNow;
        }
    }
    
    public void StartGeneration(string generationModel)
    {
        if (Status != BusinessPlanStatus.QuestionnaireComplete)
            throw new InvalidOperationException("Questionnaire must be complete before generation");
            
        Status = BusinessPlanStatus.Generating;
        GenerationStartedAt = DateTime.UtcNow;
        GenerationModel = generationModel;
    }
    
    public void CompleteGeneration()
    {
        if (Status != BusinessPlanStatus.Generating)
            throw new InvalidOperationException("Generation must be started first");
            
        Status = BusinessPlanStatus.Generated;
        GenerationCompletedAt = DateTime.UtcNow;
    }
    
    public void MoveToReview()
    {
        if (Status != BusinessPlanStatus.Generated)
            throw new InvalidOperationException("Plan must be generated before review");
            
        Status = BusinessPlanStatus.InReview;
    }
    
    public void FinalizePlan()
    {
        if (Status != BusinessPlanStatus.InReview && Status != BusinessPlanStatus.Generated)
            throw new InvalidOperationException("Plan must be generated or in review to finalize");
            
        Status = BusinessPlanStatus.Finalized;
        FinalizedAt = DateTime.UtcNow;
    }
    
    public void Archive()
    {
        Status = BusinessPlanStatus.Archived;
        ArchivedAt = DateTime.UtcNow;
    }
    
    public void Unarchive()
    {
        if (Status != BusinessPlanStatus.Archived)
            throw new InvalidOperationException("Only archived plans can be unarchived");
            
        Status = BusinessPlanStatus.Draft;
        ArchivedAt = null;
    }
    
    // Content update methods
    public void UpdateExecutiveSummary(string? content) => ExecutiveSummary = content;
    public void UpdateProblemStatement(string? content) => ProblemStatement = content;
    public void UpdateSolution(string? content) => Solution = content;
    public void UpdateMarketAnalysis(string? content) => MarketAnalysis = content;
    public void UpdateCompetitiveAnalysis(string? content) => CompetitiveAnalysis = content;
    public void UpdateSwotAnalysis(string? content) => SwotAnalysis = content;
    public void UpdateBusinessModel(string? content) => BusinessModel = content;
    public void UpdateMarketingStrategy(string? content) => MarketingStrategy = content;
    public void UpdateBrandingStrategy(string? content) => BrandingStrategy = content;
    public void UpdateOperationsPlan(string? content) => OperationsPlan = content;
    public void UpdateManagementTeam(string? content) => ManagementTeam = content;
    public void UpdateFinancialProjections(string? content) => FinancialProjections = content;
    public void UpdateFundingRequirements(string? content) => FundingRequirements = content;
    public void UpdateRiskAnalysis(string? content) => RiskAnalysis = content;
    public void UpdateExitStrategy(string? content) => ExitStrategy = content;
    public void UpdateAppendixData(string? content) => AppendixData = content;
    
    // OBNL-specific content updates
    public void UpdateMissionStatement(string? content) => MissionStatement = content;
    public void UpdateSocialImpact(string? content) => SocialImpact = content;
    public void UpdateBeneficiaryProfile(string? content) => BeneficiaryProfile = content;
    public void UpdateGrantStrategy(string? content) => GrantStrategy = content;
    public void UpdateSustainabilityPlan(string? content) => SustainabilityPlan = content;
    
    public void IncrementVersion()
    {
        Version++;
    }
}

